[env]
NEXTEST_NO_TESTS = "warn"

[tasks.build]
alias = "b"
description = "Build the project"
run = "cargo build --workspace --all-features --all-targets --release"

[tasks.docs]
description = "Build and open the docs"
run = "cargo doc --no-deps --workspace --all-features --open"

[tasks.lint]
alias = "l"
description = "Run the clippy linter"
run = "cargo clippy --all-targets --all-features --workspace"

[tasks.run]
alias = "r"
description = "Run the project"
run = "cargo run --all-features --release"

[tasks.test]
alias = "t"
description = "Run the tests"
run = "cargo llvm-cov nextest --all-features --all-targets --workspace"

[tools]
"cargo:cargo-llvm-cov" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:convco" = "latest"
dprint = "latest"
hk = "latest"
pkl = "latest"
rust = "latest"
