[package]
name = "cza"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = "1.0"
cargo-generate = "0.21"
clap.workspace = true
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
