blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/sripwoud/cza/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: 📖 Documentation
    url: https://github.com/sripwoud/cza#readme
    about: Check the README for usage instructions and examples
