[alias]
anvil = "cargo:https://github.com/foundry-rs/foundry"
cast = "cargo:https://github.com/foundry-rs/foundry"
chisel = "cargo:https://github.com/foundry-rs/foundry"
forge = "cargo:https://github.com/foundry-rs/foundry"

[env]
ANVIL_RPC_URL = "http://localhost:8545"
ANVIL_PKEY_0 = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
MISE_CARGO_BINSTALL = true
SEPOLIA_COUNTER_ADDRESS = "0xFd4364354145989210ee6d93a36B4eC7D8eC65EA"
SEPOLIA_RPC_URL = "https://ethereum-sepolia-rpc.publicnode.com"
_ = { file = ".env.yaml" }

[tasks."build.contracts"]
alias = "bc"
dir = "contracts"
description = "Build the contracts"
run = "forge b"
quiet = true

[tasks."build.wagmi"]
alias = "bw"
description = "Build type safe wagmi hooks and functions"
dir = "web"
run = "bun wagmi generate"
quiet = true

[tasks."build.web"]
alias = "bw"
description = "Build the project"
dir = "web"
run = ["bun tsc -b", "bun vite build"]
quiet = true

[tasks."dev.deploy.sha256.anvil"]
dir = "contracts"
hide = true
run = """
# wait for anvil to start
sleep 2
forge script \
      "Verifier_sha256_32Script" \
      --broadcast \
      --rpc-url $ANVIL_RPC_URL \
      --private-key $ANVIL_PKEY_0
"""
quiet = true

[tasks."dev.anvil"]
alias = "a"
description = "Start anvil local ethereum testnet node"
run = "anvil"

[tasks."dev.web"]
description = "Start the dev web client"
run = "bun vite"
quiet = true

[tasks.dev]
alias = "d"
depends = "dev.*"
description = "Start dev network and web client"
dir = "web"
quiet = true

[tasks.preview]
alias = "p"
description = "Preview the app"
dir = "web"
run = "bun vite preview"
quiet = true

[tasks.test]
alias = "t"
description = "Run all tests"
depends = "test.*"
quiet = true

[tasks."test.circuits"]
alias = "tci"
description = "Run the circuits tests"
dir = "circuits"
run = "bun test"
quiet = true

[tasks."test.contracts"]
alias = "tco"
description = "Run the contracts tests"
dir = "contracts"
run = "forge test"
quiet = true

[tools]
bun = "latest"
cargo-binstall = "latest"
"cargo:convco" = "latest"
"cargo:soldeer" = "latest"
dprint = "latest"
hk = "latest"
"npm:@biomejs/biome" = "latest"
"npm:solhint" = "latest"
"npm:typescript" = "latest"
pkl = "latest"
anvil = { version = "tag:stable", bin = "anvil" }
cast = { version = "tag:stable", bin = "cast" }
chisel = { version = "tag:stable", bin = "chisel" }
forge = { version = "tag:stable", bin = "forge" }
"cargo:https://github.com/iden3/circom.git" = { version = "latest" }
